name: grits
channels:
  - conda-forge
dependencies:
  - cmeutils >= 1.2.0
  - ele
  - freud >= 3.0
  - gsd >= 3.0
  - jupyterlab
  - mbuild
  - ele
  - numpy
  - openbabel
  - pip
  - python >= 3.10
  - py3Dmol
  - pytest
  - pytest-cov
  - pre-commit
