name: grits
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - ele
  - freud>=2.13.1
  - gsd>=3.0
  - jupyterlab
  - mbuild
  - ele
  - freud
  - openbabel
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - rdkit
